#pragma once

#define TAPPING_TERM 125
#define TAPPING_TERM_PER_KEY

#define PLOOPY_DPI_OPTIONS { 800, 1200, 1600 }
#define PLOOPY_DPI_DEFAULT 1

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 128.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 128.0
#define PLOOPY_DRAGSCROLL_INVERT
